"""
Automated Report Generation Agent
Creates comprehensive, executive-ready reports from pipeline results
"""
import pandas as pd
import numpy as np
import logging
import os
from datetime import datetime
from typing import Dict, List, Any, Optional
from pathlib import Path


class ReportGenerationAgent:
    """
    Automated Report Generation Agent
    Creates comprehensive HTML and PDF reports from pipeline execution
    """

    def __init__(self, config: Dict[str, Any], artifacts_path: str):
        self.config = config
        self.artifacts_path = Path(artifacts_path)
        self.logger = logging.getLogger(self.__class__.__name__)

        self.artifacts_path.mkdir(parents=True, exist_ok=True)

        # Configuration
        self.include_executive_summary = config.get('executive_summary', True)
        self.include_visualizations = config.get('include_visualizations', True)
        self.include_recommendations = config.get('include_recommendations', True)
        self.format = config.get('format', 'html')  # html, markdown, or both

    def generate_comprehensive_report(
        self,
        data: pd.DataFrame,
        quality_report: Any,
        cleaning_report: Any,
        insight_report: Any,
        anomaly_report: Optional[Any] = None,
        feature_report: Optional[Any] = None
    ) -> str:
        """
        Generate comprehensive report from all pipeline stages
        """
        self.logger.info("📊 Generating comprehensive pipeline report...")

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"pipeline_report_{timestamp}.html"
        filepath = self.artifacts_path / filename

        # Build HTML report
        html_content = self._build_html_report(
            data, quality_report, cleaning_report, insight_report,
            anomaly_report, feature_report
        )

        # Save report
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)

        self.logger.info(f"✅ Report generated: {filepath}")
        return str(filepath)

    def _build_html_report(
        self, data, quality_report, cleaning_report, insight_report,
        anomaly_report, feature_report
    ) -> str:
        """Build comprehensive HTML report"""

        # Executive Summary
        exec_summary = self._generate_executive_summary(
            data, quality_report, cleaning_report, anomaly_report, feature_report
        )

        # Quality Assessment Section
        quality_section = self._generate_quality_section(quality_report)

        # Data Cleaning Section
        cleaning_section = self._generate_cleaning_section(cleaning_report)

        # Anomaly Detection Section
        anomaly_section = ""
        if anomaly_report:
            anomaly_section = self._generate_anomaly_section(anomaly_report)

        # Feature Engineering Section
        feature_section = ""
        if feature_report:
            feature_section = self._generate_feature_section(feature_report)

        # Insights Section
        insights_section = self._generate_insights_section(insight_report)

        # Recommendations
        recommendations_section = self._generate_recommendations_section(
            quality_report, cleaning_report, anomaly_report, feature_report
        )

        # Combine all sections
        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agentic Data Pipeline - Comprehensive Report</title>
    <style>
        {self._get_css_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🤖 Agentic Data Pipeline Report</h1>
            <p class="subtitle">Automated Data Analysis & Processing</p>
            <p class="timestamp">Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
        </header>

        {exec_summary}
        {quality_section}
        {cleaning_section}
        {anomaly_section}
        {feature_section}
        {insights_section}
        {recommendations_section}

        <footer>
            <p>Generated by Agentic Data Pipeline v1.0</p>
            <p>Powered by AI Agents: Inspector, Refiner, Anomaly Detector, Feature Engineer, Insight Generator</p>
        </footer>
    </div>
</body>
</html>
"""
        return html

    def _generate_executive_summary(
        self, data, quality_report, cleaning_report, anomaly_report, feature_report
    ) -> str:
        """Generate executive summary section"""
        original_shape = cleaning_report.original_shape if cleaning_report else data.shape
        final_shape = data.shape
        quality = quality_report.overall_quality.value if quality_report else "unknown"

        # Calculate key metrics
        data_reduction = ((original_shape[0] - final_shape[0]) / original_shape[0] * 100) if original_shape[0] > 0 else 0
        cols_added = final_shape[1] - original_shape[1]

        anomaly_info = ""
        if anomaly_report:
            anomaly_info = f"""
            <div class="metric">
                <div class="metric-label">Anomalies Detected</div>
                <div class="metric-value">{anomaly_report.anomaly_count}</div>
                <div class="metric-detail">{anomaly_report.anomaly_percentage:.1f}% of data</div>
            </div>
            """

        feature_info = ""
        if feature_report:
            feature_info = f"""
            <div class="metric">
                <div class="metric-label">Features Engineered</div>
                <div class="metric-value">{feature_report.new_features}</div>
                <div class="metric-detail">ML-ready features</div>
            </div>
            """

        return f"""
        <section class="executive-summary">
            <h2>📈 Executive Summary</h2>
            <div class="metrics-grid">
                <div class="metric">
                    <div class="metric-label">Data Quality</div>
                    <div class="metric-value quality-{quality}">{quality.upper()}</div>
                    <div class="metric-detail">Overall assessment</div>
                </div>
                <div class="metric">
                    <div class="metric-label">Original Dataset</div>
                    <div class="metric-value">{original_shape[0]:,} × {original_shape[1]}</div>
                    <div class="metric-detail">rows × columns</div>
                </div>
                <div class="metric">
                    <div class="metric-label">Final Dataset</div>
                    <div class="metric-value">{final_shape[0]:,} × {final_shape[1]}</div>
                    <div class="metric-detail">{abs(data_reduction):.1f}% {'reduction' if data_reduction > 0 else 'growth'}</div>
                </div>
                {anomaly_info}
                {feature_info}
            </div>
        </section>
        """

    def _generate_quality_section(self, quality_report) -> str:
        """Generate quality assessment section"""
        if not quality_report:
            return ""

        # Top issues
        top_recommendations = quality_report.recommendations[:5]
        rec_html = "".join([
            f"<li class='recommendation-item'>{rec}</li>"
            for rec in top_recommendations
        ])

        # Quality scores
        low_quality_cols = [
            (col, score) for col, score in quality_report.column_quality_scores.items()
            if score < 0.7
        ]
        low_quality_cols.sort(key=lambda x: x[1])

        quality_table = ""
        if low_quality_cols:
            quality_rows = "".join([
                f"<tr><td>{col}</td><td><div class='score-bar' style='width: {score*100}%'></div>{score:.2f}</td></tr>"
                for col, score in low_quality_cols[:10]
            ])
            quality_table = f"""
            <h3>Low Quality Columns</h3>
            <table>
                <tr><th>Column</th><th>Quality Score</th></tr>
                {quality_rows}
            </table>
            """

        return f"""
        <section>
            <h2>🔍 Data Quality Assessment</h2>
            <div class="info-box">
                <p><strong>Overall Quality:</strong> <span class="badge quality-{quality_report.overall_quality.value}">{quality_report.overall_quality.value.upper()}</span></p>
                <p><strong>Missing Values:</strong> {sum(quality_report.missing_values.values()):.0f} total across {len([v for v in quality_report.missing_values.values() if v > 0])} columns</p>
                <p><strong>Duplicates:</strong> {quality_report.duplicate_count} rows</p>
                <p><strong>Outliers:</strong> {quality_report.outlier_count} detected</p>
            </div>

            <h3>Key Issues Identified</h3>
            <ul class="recommendations-list">
                {rec_html}
            </ul>

            {quality_table}
        </section>
        """

    def _generate_cleaning_section(self, cleaning_report) -> str:
        """Generate data cleaning section"""
        if not cleaning_report:
            return ""

        actions_html = "".join([
            f"<li>✓ {action}</li>"
            for action in cleaning_report.actions_taken
        ])

        cols_dropped = ", ".join(cleaning_report.columns_dropped) if cleaning_report.columns_dropped else "None"

        return f"""
        <section>
            <h2>🧹 Data Cleaning Results</h2>
            <div class="info-box">
                <p><strong>Original Shape:</strong> {cleaning_report.original_shape[0]:,} rows × {cleaning_report.original_shape[1]} columns</p>
                <p><strong>Cleaned Shape:</strong> {cleaning_report.cleaned_shape[0]:,} rows × {cleaning_report.cleaned_shape[1]} columns</p>
                <p><strong>Rows Removed:</strong> {cleaning_report.rows_removed:,}</p>
                <p><strong>Columns Dropped:</strong> {len(cleaning_report.columns_dropped)}</p>
            </div>

            <h3>Actions Taken</h3>
            <ul class="actions-list">
                {actions_html}
            </ul>

            <h3>Columns Dropped</h3>
            <p class="detail-text">{cols_dropped}</p>
        </section>
        """

    def _generate_anomaly_section(self, anomaly_report) -> str:
        """Generate anomaly detection section"""
        if not anomaly_report:
            return ""

        # Top anomaly features
        top_features = list(anomaly_report.feature_importance.items())[:5]
        feature_rows = "".join([
            f"<tr><td>{name}</td><td><div class='score-bar importance' style='width: {score*100}%'></div>{score:.3f}</td></tr>"
            for name, score in top_features
        ])

        recommendations_html = "".join([
            f"<li>{rec}</li>"
            for rec in anomaly_report.recommendations
        ])

        return f"""
        <section>
            <h2>🚨 Anomaly Detection Results</h2>
            <div class="info-box alert">
                <p><strong>Method:</strong> {anomaly_report.method}</p>
                <p><strong>Anomalies Detected:</strong> {anomaly_report.anomaly_count} ({anomaly_report.anomaly_percentage:.2f}%)</p>
            </div>

            <h3>Top Anomaly Indicators</h3>
            <table>
                <tr><th>Feature</th><th>Importance</th></tr>
                {feature_rows}
            </table>

            <h3>Recommendations</h3>
            <ul class="recommendations-list">
                {recommendations_html}
            </ul>
        </section>
        """

    def _generate_feature_section(self, feature_report) -> str:
        """Generate feature engineering section"""
        if not feature_report:
            return ""

        transformations_html = "".join([
            f"<li>✓ {trans}</li>"
            for trans in feature_report.transformations_applied
        ])

        # Group features by type
        feature_types = {}
        for feat in feature_report.features_created:
            ftype = feat['type']
            if ftype not in feature_types:
                feature_types[ftype] = 0
            feature_types[ftype] += 1

        type_rows = "".join([
            f"<tr><td>{ftype}</td><td>{count}</td></tr>"
            for ftype, count in feature_types.items()
        ])

        return f"""
        <section>
            <h2>⚙️ Feature Engineering Results</h2>
            <div class="info-box success">
                <p><strong>Original Features:</strong> {feature_report.original_features}</p>
                <p><strong>New Features Created:</strong> {feature_report.new_features}</p>
                <p><strong>Total Features:</strong> {feature_report.total_features}</p>
            </div>

            <h3>Feature Types Created</h3>
            <table>
                <tr><th>Type</th><th>Count</th></tr>
                {type_rows}
            </table>

            <h3>Transformations Applied</h3>
            <ul class="actions-list">
                {transformations_html}
            </ul>
        </section>
        """

    def _generate_insights_section(self, insight_report) -> str:
        """Generate insights section"""
        if not insight_report:
            return ""

        insights_html = "".join([
            f"<li>{insight}</li>"
            for insight in insight_report.key_insights
        ])

        plots_html = "".join([
            f"<li>📊 {plot}</li>"
            for plot in insight_report.plots_generated
        ])

        return f"""
        <section>
            <h2>💡 Key Insights</h2>
            <ul class="insights-list">
                {insights_html}
            </ul>

            <h3>Visualizations Generated</h3>
            <ul class="plots-list">
                {plots_html}
            </ul>
        </section>
        """

    def _generate_recommendations_section(
        self, quality_report, cleaning_report, anomaly_report, feature_report
    ) -> str:
        """Generate consolidated recommendations"""
        all_recommendations = []

        if quality_report:
            all_recommendations.extend(quality_report.recommendations[:3])

        if anomaly_report:
            all_recommendations.extend(anomaly_report.recommendations[:2])

        if feature_report:
            all_recommendations.extend(feature_report.recommendations[:2])

        rec_html = "".join([
            f"<li class='recommendation-item'>{rec}</li>"
            for rec in all_recommendations[:10]
        ])

        return f"""
        <section class="recommendations-final">
            <h2>🎯 Final Recommendations</h2>
            <ul class="recommendations-list">
                {rec_html}
            </ul>
        </section>
        """

    def _get_css_styles(self) -> str:
        """Return CSS styles for the report"""
        return """
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 20px;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 10px;
            box-shadow: 0 10px 50px rgba(0,0,0,0.2);
            overflow: hidden;
        }
        header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }
        header h1 { font-size: 2.5em; margin-bottom: 10px; }
        .subtitle { font-size: 1.2em; opacity: 0.9; }
        .timestamp { font-size: 0.9em; opacity: 0.8; margin-top: 10px; }
        section {
            padding: 40px;
            border-bottom: 1px solid #eee;
        }
        section:last-of-type { border-bottom: none; }
        h2 {
            color: #667eea;
            margin-bottom: 20px;
            font-size: 1.8em;
            border-bottom: 3px solid #667eea;
            padding-bottom: 10px;
        }
        h3 {
            color: #555;
            margin: 25px 0 15px 0;
            font-size: 1.3em;
        }
        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin: 20px 0;
        }
        .metric {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            border-left: 4px solid #667eea;
        }
        .metric-label {
            font-size: 0.9em;
            color: #666;
            margin-bottom: 10px;
        }
        .metric-value {
            font-size: 2em;
            font-weight: bold;
            color: #333;
            margin-bottom: 5px;
        }
        .metric-detail {
            font-size: 0.85em;
            color: #888;
        }
        .quality-excellent { color: #28a745; }
        .quality-good { color: #17a2b8; }
        .quality-fair { color: #ffc107; }
        .quality-poor { color: #dc3545; }
        .badge {
            display: inline-block;
            padding: 5px 15px;
            border-radius: 20px;
            font-size: 0.9em;
            font-weight: bold;
        }
        .badge.quality-excellent { background: #d4edda; color: #155724; }
        .badge.quality-good { background: #d1ecf1; color: #0c5460; }
        .badge.quality-fair { background: #fff3cd; color: #856404; }
        .badge.quality-poor { background: #f8d7da; color: #721c24; }
        .info-box {
            background: #f8f9fa;
            border-left: 4px solid #667eea;
            padding: 20px;
            margin: 20px 0;
            border-radius: 5px;
        }
        .info-box.alert { border-left-color: #ffc107; background: #fff3cd; }
        .info-box.success { border-left-color: #28a745; background: #d4edda; }
        .info-box p { margin: 10px 0; }
        ul { margin: 15px 0; padding-left: 20px; }
        li { margin: 8px 0; }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background: #f8f9fa;
            font-weight: 600;
            color: #555;
        }
        .score-bar {
            height: 20px;
            background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);
            border-radius: 10px;
            display: inline-block;
            margin-right: 10px;
        }
        .score-bar.importance {
            background: linear-gradient(90deg, #ffc107 0%, #ff6b6b 100%);
        }
        footer {
            background: #f8f9fa;
            padding: 30px;
            text-align: center;
            color: #666;
            font-size: 0.9em;
        }
        footer p { margin: 5px 0; }
        """
